# Generated by Django 4.2.7 on 2025-08-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='remote_addr',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='headers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
